name: Azure SQL for GitHub Actions

on:
push:
    branches: [ master ]
workflow_dispatch:

jobs:
build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1
    with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

- uses: azure/sql-action@v1
  with:
    server-name: SQL_SERVER_NAME
    connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
   # sql-file: './Database.dacpac'

    # Azure logout 
- name: logout
  run: |
     az logout
