name: Deploying dacpac 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    env:
      db_user: ${{ secrets.SQL_username }}
      db_password: ${{ secrets.SQL_password }}
      database: AdventureWorks2016
      DB_SERVER: twsql2b
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2

    - name: setup-sqlpackage
      uses: coreywebber/setup-sqlpackage@v1.0.0

    - name: Restoring the database
      run: sqlpackage /Action:Import /sf:${{github.workspace}}\AdventureWorks2016.dacpac /tsn:${{env.DB_SERVER}} /tdn:${{env.database}} /tu:${{env.db_user}} /tp:${{ env.db_password }} /p:DatabaseMaximumSize=2 /p:DatabaseEdition=Basic
