name: Extracting dacpac 

on:
  workflow_dispatch:
defaults:
  run:
    working-directory: C:\Program Files\Microsoft SQL Server\150\DAC\bin
jobs:
  build:
    runs-on: self-hosted
    env:
      database: AdventureWorks2016
      DB_SERVER: twsqlcl2a
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2

    - name: Extracting Dacpac 
      run: sqlpackage /Action:Extract /Tf:${{github.workspace}}\AdventureWorks2016.dacpac /ssn:${{env.DB_SERVER}} /sdn:${{env.database}} 
