name: Extracting dacpac 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    env:
      database: AdventureWorks2016
      DB_SERVER: twsqlcl2a
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2

    - name: Restoring the database
      run: sqlpackage /Action:Extract /Tf:${{github.workspace}}\AdventureWorks2016.dacpac /ssn:${{env.DB_SERVER}} /sdn:${{env.database}} 
